[package]
name = "mini-redis-common-rs"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde_json = "1.0.148"
tokio = { version = "1.48.0", features = [
    'rt',
    'rt-multi-thread',
    'macros',
    'fs',
    "io-util",
    "sync",
    "time",
    "signal",
    "net",
] }
